Updating the deploy-apps script
parca-dev/parca-demo pull request #29
Opened 2022-12-01 06:08 UTC by QuinceyJames

# Problem
- Currently, the deploy-apps.sh script has no way of selectively choosing which apps to deploy. This means that users will have to wait a while for all the apps to build. Further, running all of these apps is resource-intensive. 

# Changes
- Edited the deploy-apps.sh script to allow the user to choose which apps to deploy
- updated the readme to include an example of how to use the script

# Issues
- Fixes #26

2022-12-01 06:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/parca-dev/parca-demo?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/parca-dev/parca-demo?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/parca-dev/parca-demo?pullRequest=29) it.</sub>

2022-12-01 06:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/parca-dev/parca-demo?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/parca-dev/parca-demo?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/parca-dev/parca-demo?pullRequest=29) it.</sub>

2022-12-01 06:18 UTC, QuinceyJames commented
Hi there! Thanks for creating such a cool project. This is my first time contributing to something open source so please forgive any blatant mistakes I made 😄

2022-12-01 08:13 UTC, kakkoyun approved these changes
LGTM.
It is really fancy! Thanks for the contribution.
I have just one nit suggestion.

@maxbrunet What do you think?

2022-12-01 18:08 UTC, maxbrunet requested changes
Fancy indeed! :sparkles:

Just a few comments to ensure we do not fall into odd states

I am going to enable some linters on the repo and once these pass on the PR, we can get it merged

2022-12-02 03:20 UTC, QuinceyJames commented on deploy-apps.sh
> +buildSelectedDeployments
EOF Blank line added

2022-12-02 03:21 UTC, QuinceyJames commented on deploy-apps.sh
>  #!/bin/bash
- Shebang updated
- Strict mode added

2022-12-02 03:22 UTC, QuinceyJames commented on deploy-apps.sh
> +  echo "Building the '$1' demo"
- print statement fixed

2022-12-02 03:23 UTC, QuinceyJames commented on deploy-apps.sh
> +  for file in "${DEPLOYMENTS_GLOB[@]}" ;  do
- local variables used (but please double check I didn't miss any)

2022-12-02 03:32 UTC, QuinceyJames commented
Thanks so much for your feedback! Never heard of strict mode before -- it caught some strange behavior in ```findDeploymentIndexFromInteger```.

Btw I'm not sure if I am meant to mark the conversations as resolved or if I leave that you.

Also, should I pull in the linter changes from your repo into my fork and run it? Or will Github warn me automatically? 

Thanks again!

2022-12-02 03:38 UTC, maxbrunet commented
> Thanks so much for your feedback! Never heard of strict mode before -- it caught some strange behavior in `findDeploymentIndexFromInteger`.

You're welcome!

> Btw I'm not sure if I am meant to mark the conversations as resolved or if I leave that you.

Yes, I think you can resolve them

> Also, should I pull in the linter changes from your repo into my fork and run it? Or will Github warn me automatically?

If you want to get a head start, you can run `shellcheck deploy-apps.sh` locally: https://github.com/koalaman/shellcheck#installing
It's mostly this one that may give you trouble.

2022-12-02 15:35 UTC, kakkoyun commented
@QuinceyJames Could you please rebase? Now we have some CI checks, I'm good to merge when the CI is green https://github.com/parca-dev/parca-demo/pull/31/files

2022-12-02 18:03 UTC, maxbrunet approved these changes
Great work! Thank you!

2022-12-02 18:03 UTC, merged